### ISSUE TITLE
NfcManager.start() does not continue to following .then()

### ISSUE THREAD

**Issue by jameswingate** [whitedogg13/react-native-nfc-manager#74] opened 2018-08-02 19:07 UTC
Hi there, I'm having an issue with using NfcManager in my app - even if I use a direct copy of the example provided in the repo. The following code snippet runs perfectly, as far as I can tell:

```
NfcManager.start({
    onSessionClosedIOS: () => {
        console.warn('ios session closed');
        NfcManager.unregisterTagEvent();
    }
})
```

However, a `console.warn` informs me that `unregisterTagEvent` fails due to the reason "Not even registered". Despite this not really causing an issue with my app, the `.then()` statement following the above code snippet also doesn't ever get called. How might I go about fixing this?

```
NfcManager.start({
    onSessionClosedIOS: () => {
        console.warn('ios session closed');
        NfcManager.unregisterTagEvent();
    }
})
.then(result => {
    console.warn('start OK', result);
})
.catch(error => {
    console.warn('start fail', error);
    this.setState({supported: false});
})
```

I am using the latest version of react-native-nfc-manager.

**Comment by whitedogg13** [comment] 2018-08-13 13:01
Hi, sorry for the late response!

The issue is related to the event subscription not properly cleared when the iOS reader session closed. It should be should be fixed in the latest 0.5.4 release. Thanks for reporting!

**Closed** 2018-08-27 14:28 UTC
